# Dockerfile.client

FROM ubuntu:20.04

# Install required packages
RUN apt-get update && \
    apt-get install -y mosquitto-clients && \
    rm -rf /var/lib/apt/lists/*

# Copy the client script
COPY client.sh /client.sh
RUN chmod +x /client.sh

# Set the entrypoint
ENTRYPOINT ["/client.sh"]
